// <auto-generated />
using System;
using BackendAerolinea;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BackendAerolinea.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20230611164251_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BackendAerolinea.Models.Aeropuerto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("LimiteAviones_")
                        .HasColumnType("int");

                    b.Property<string>("NombreAeropuerto_")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Aeropuerto");
                });

            modelBuilder.Entity("BackendAerolinea.Models.Avion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Aeropuertollegada_")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Aeropuertosalida_")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeSpan>("Horallegada_")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("Horasalida_")
                        .HasColumnType("time");

                    b.Property<int>("LimitePeso_")
                        .HasColumnType("int");

                    b.Property<string>("NombreAvion_")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PasajerosLimite")
                        .HasColumnType("int");

                    b.Property<string>("StatusVuelo_")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Avion");
                });

            modelBuilder.Entity("BackendAerolinea.Models.Pasajero", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AvionId_")
                        .HasColumnType("int");

                    b.Property<string>("NombrePasajero_")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PesoEquipaje_")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("pasajeros");
                });
#pragma warning restore 612, 618
        }
    }
}
